data_paths:
  nhanes_2017_2020_raw: "data/raw/nhanes_2017_2020/"
  yale_raw: "data/raw/yale_cohort/yale_data.csv"
  nhanes_iii_raw: "data/raw/nhanes_iii/adult.dat"
  nhanes_iii_sas: "data/raw/nhanes_iii/adult.sas"
  processed_train: "data/processed/nhanes_2017_2020_train.csv"
  processed_val: "data/processed/yale_validation.csv"
  processed_prog: "data/processed/nhanes_iii_prognostication.csv"

model:
  output_path: "outputs/models/xgboost_model.pkl"
  hyperparameters:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    objective: "binary:logistic"  # Adjust based on your task

results:
  metrics_dir: "outputs/results/"
